name:                maintainable-software-architecture-in-haskell
version:             0.1.0.0
github:              "EncodePanda/maintainable-software-architecture-in-haskell"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/EncodePanda/maintainable-software-architecture-in-haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  maintainable-software-architecture-in-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - maintainable-software-architecture-in-haskell

tests:
  maintainable-software-architecture-in-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - maintainable-software-architecture-in-haskell
